export function canAccessOrder(input: { isAdmin: boolean; buyerId: number | string; userId: number | string }): boolean;
export function canAccessSellerItem(input: { isAdmin: boolean; sellerId: string | null; userSellerId: string | null }): boolean;
export function canCancelOrder(status: "pending_payment" | "paid" | "processing" | "delivered" | "cancelled" | "refunded" | "failed" | string): boolean;
export function canRefundOrder(input: { orderStatus: "pending_payment" | "paid" | "processing" | "delivered" | "cancelled" | "refunded" | "failed" | string; paymentStatus: "pending" | "paid" | "failed" | "expired" | "refunded" | string | null }): boolean;
export function canMarkFailed(status: "pending_payment" | "paid" | "processing" | "delivered" | "cancelled" | "refunded" | "failed" | string): boolean;
export function shouldProcessWebhookOrder(status: "pending_payment" | "paid" | "processing" | "delivered" | "cancelled" | "refunded" | "failed" | string): boolean;
export function canClaimAutoStock(status: "available" | "reserved" | "sold" | "disabled" | string): boolean;
export function canCheckout(settings: { checkoutEnabled: boolean } | null | undefined): boolean;
export function isWebhookAmountMatch(paymentAmount: number, webhookAmount: number): boolean;
export function isDuplicatePaidWebhook(paymentStatus: "pending" | "paid" | "failed" | "expired" | "refunded" | string): boolean;
export function resolveWebhookPaymentOutcome(input: { orderStatus: "pending_payment" | "paid" | "processing" | "delivered" | "cancelled" | "refunded" | "failed" | string; paymentStatus: "pending" | "paid" | "failed" | "expired" | "refunded" | string; paymentAmount: number; webhookAmount: number }): "paid" | "duplicate" | "ignored" | "mismatch";
